### ISSUE TITLE
Clicking Options toggles hidden torrents instead of bringing up Options

### ISSUE THREAD

**Issue by tordenflesk** [ceodoe/noshitempornium#2]
Waterfox Classic 2020.09 / Violentmonkey v2.12.7

**Comment by ceodoe** [comment]
Thanks for the report. Unfortunately, Waterfox is not supported, and Violentmonkey is not supported, only Tampermonkey is. 

I'm guessing this is because your browser or userscript engine doesn't support [event.stopPropagation()](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation), which is used to stop sending the click event to elements behind the receiving button. You'll need to switch to Tampermonkey or use a different browser.

https://github.com/ceodoe/noshitempornium/blob/42c25df57c2ad8c5df670b8fa026917d42731d02/NoShitEmpornium.user.js#L843-L846
